
language: node_js

node_js:
  - '6'

sudo: required

before_install:
  - sudo bash sh/ci/before-install.sh

before_script:
  - chmod -R +x sh
  - export CXX=g++-6
  - export SKIP_QUICK_TEST=TRUE
  - export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig

before_deploy:
  - source ./sh/deploy/before.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file: $(./sh/deploy/file.sh)
  on:
    tags: true

after_deploy:
  - source ./sh/deploy/after.sh
