
language: node_js

node_js:
  - '6'

before_script:
  - chmod -R +x sh
  - export CXX=g++-6
  - export SKIP_QUICK_TEST=TRUE

before_deploy:
  - source ./sh/deploy/before.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gtkmm-3.0

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file: $(./sh/deploy/file.sh)
  on:
    tags: true

after_deploy:
  - source ./sh/deploy/after.sh
